public enum ErrorCode {
  COURSE_INVALID_DURATION,      // 1..100
  COURSE_INVALID_TITLE,         // пустой заголовок
  COURSE_INVALID_COMPLETED,     // completed > duration или < 0
  COURSE_CODE_BLANK,
  COURSE_CODE_BAD_LENGTH,
  COURSE_CODE_BAD_CHARS,
  IMPORT_MALFORMED_RECORD,
  IMPORT_IO_ERROR,
  ENROLL_CLOSED,
  ENROLL_FULL,
  ENROLL_PREREQ_MISSING,
  ENROLL_ALREADY,
  STORE_DUPLICATE_ID,
  HUB_INVALID_ARGUMENT,
  HUB_UNEXPECTED
}